### ISSUE TITLE
NL Topo App: sommige buttons werken niet

### ISSUE THREAD

**Issue by GijsLooijen** [map5nl/map5issues#24]
Huawei P9, Firefox, Android 7.0

 - find, print, en 'open eigen data' button werken bij mij niet. Locator, kaartlaag en zoomfuncties werken prima.

- andere opmerking nog: de kaart is nu altijd north-up. Zou fijn zijn als er een functie opzat zoals die (zoals het bij Garmin heet) 'track up' heet. Dus de kaart draait dan meer met de richting waarin ik loop, of in dit geval kijk/wijs met mn telefoon.

- laatste, maar dat gaat meer over Kadviewer denk ik: ik mis een laag met Belvedere-gebieden (of zie 'm zo snel niet)

**Comment by justb4** [comment]
Bedankt. Heb gechecked op mijn phone: Fairphone2, Android 5.1, Chrome browser: find, print (PDF), en 'open eigen data' werken ok, kan zelfs GPX laden vanuit Dropbox. Dus moet iets met jouw setup te maken hebben. Heb je de Chrome browser al geprobeerd? 

Kun je voor de andere opmerkingen, ook waardevol, aparte issues openen?

**Comment by GijsLooijen** [comment]
op chrome doet alles het wel idd.


2017-04-19 12:39 GMT+02:00 Just van den Broecke <notifications@github.com>:

**Comment by justb4** [comment]
Outdated, re-open when needed.
