### ISSUE TITLE
TOPO NL APP: 'track-up' viewmodus ipv alleen 'north-up'?

### ISSUE THREAD

**Issue by GijsLooijen** [map5nl/map5issues#25]
de kaart is nu altijd north-up. Zou fijn zijn als er een functie opzat zoals die (zoals het bij Garmin heet) 'track up' heet. Dus de kaart draait dan meer met de richting waarin ik loop, of in dit geval kijk/wijs met mn telefoon. 

Handig voor bij het wandelen, maar pakweg ook (zoals ik erop kwam) in het veld als je probeert een niet-meer bestaande weg (in mijn geval eentje van de 1850-kaart) exact probeert na te lopen.

**Comment by justb4** [comment]
Dit gaat voorlopig niet gebeuren in nltopo, is meer een demo app, niet echt een 'veld-app", , mogelijk in nieuw te maken, echte mobiele map5 app.
